### ISSUE TITLE
[Feature] Add Courseweb link to module card

### ISSUE THREAD

**Issue by russellpeiris** [pawan-live/timetable-app#148]
Adding the course link will eliminate the need to open courseweb in a new window, as a result we can access courseweb right from the app.

**Comment by pawan-live** [comment]
Thanks Russel, but the feature is already there!, just add the `link` field to the module object in the json and the link will appear in the respective card!

**Comment by pawan-live** [comment]
If you have some free time pls do add the data where it's needed 😄
