### ISSUE TITLE
Extend the api to add weekend time tables as well

### ISSUE THREAD

**Issue by methmal66** [pawan-live/timetable-app#49]
Currently data is stored for weekend students only. But those are not specified as weekend. Then which format to follow when adding weekend time tables? Denote weekend batches from negatives (ex: -01 means WE batch 1 of given specialization) is an one option.
Else we have to refactor the entire `data.json` to make it compatible with weekend as well. That is very work intensive. So i would not recommend that. 

Then add another field in the home page as `Batch type` or something like that. That will choose between weekdays and weekend. So items under sub group can be dynamically inserted according to that choice.

**Comment by pawan-live** [comment]
Currently, weekend batches are added as well, inside each specialization, just same as a normal subgroup. I used the prefix `WE` in front of the group number. (only added in SE for now). An image is attached below.

[![Screenshot-2022-07-29-at-10-04-32.png](https://i.postimg.cc/2y22pfXn/Screenshot-2022-07-29-at-10-04-32.png)](https://postimg.cc/vxxW9Cym)

**Comment by methmal66** [comment]
Yes, you guy developing it pretty fast. I almost missed that :). Btw you can just provide the [commit](https://github.com/pawan-live/timetable-app/commit/7b452061b8df05a8c8168919433cd349632b2f28) like this. So no need to get screenshots. And it helps to track everything.
