### ISSUE TITLE
Greet on first interactions

### ISSUE THREAD

**Issue by methmal66** [pawan-live/timetable-app#50]
Most of the contributors are still learning to program. So there is a good chance to make their first PR or issue for this repo. So it would nice appreciate them for getting started with open source. It can be configured using github actions under 2 minutes. I use it all the times and it makes contributors super exiting.

**Comment by pawan-live** [comment]
It'd be great if you could add this feature and thanks for the suggestion

**Comment by pawan-live** [comment]
I will work on it. (forgot that it exists in repository settings 😂)

**Comment by methmal66** [comment]
I wish i could. But the thing is, it needs a Github repository secret. That can be only configured by the repo owner.

**Comment by pawan-live** [comment]
@methmal66 thanks for suggesting, I added the workflow 🎉
