### ISSUE TITLE
Change the No lectures message

### ISSUE THREAD

**Issue by DKDinushaPerera** [pawan-live/timetable-app#53]
When its Friday and we are viewing next day timetable, and if there are no lectures, the display msg should be 'no lectures **tomorrow**' but when the current date is Saturday it should show as no lectures **today**

**Comment by sudofinn** [comment]
Fixed this issue as seen in pr.

**Comment by pawan-live** [comment]
Thanks @sudofinn for helping, but I think there was a miscommunication with the issue description. 🥲 
I think what @DKDinushaPerera meant was, when we are viewing a timetable of another day, it should display as 'No lectures for <that particular day>'
For example let's say, we are viewing the table of friday, then it should show 'No lectures for Friday'
Saturday was just an example 🥲
However I will fix this! Thanks again

**Comment by pawan-live** [comment]
I'm working on it

**Comment by sudofinn** [comment]
Alright, sorry for my misunderstanding

**Comment by pawan-live** [comment]
@sudofinn no worries man! it's fine! 😀
