### ISSUE TITLE
Time slot not matching

### ISSUE THREAD

**Issue by It21165498** [pawan-live/timetable-app#71]
In 3.1 timetable, on Monday oop lectures+tute time slot should be 8.30 - 11.30 . (Not 8.30 - 10.30)

**Comment by pawan-live** [comment]
@IndudiniThennakoon

**Comment by IndudiniThennakoon** [comment]
> @IndudiniThennakoon



> In 3.1 timetable, on Monday oop lectures+tute time slot should be 8.30 - 11.30 . (Not 8.30 - 10.30)

Thank you so much. We will fix it

**Comment by pawan-live** [comment]
@It21165498 , issue fixed by @IndudiniThennakoon , will merge to the main branch soon
